apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-spring-deploy
  labels:
    bank: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      bank: spring
  template:
    metadata:
      name: bank-spring-pod
      labels:
        bank: spring
    spec:
      containers:
        - name: bank-spring-cont
          image: adhmabdein/springbank
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://banksvc:3306/bankappdb?allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bank-mysql-secret
                  key: MYSQL_PASSWORD    

