apiVersion: v1
kind: Service
metadata:
  name: bank-spring-svc
spec:
  selector:
    bank: spring
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30033    
